@startuml
class User {
    + int id
    + String username
    + String email
    + String password
    + String role
}

class Family {
    + int id
    + String familyName
    + String description
}

class Type {
    + int id
    + String typeName
    + String description
    + Family family
}

class Specimen {
    + int id
    + String name
    + Type type
    + Family family
    + String gender
    + String countryOfOrigin
    + LocalDate dateOfEntry
    + String imageUrl
}

User "1" -- "0..*" Specimen
Family "1" -- "0..*" Type
Type "1" -- "0..*" Specimen
@enduml
